"""materias_primas2

Revision ID: 63ddeee8117a
Revises: bb0bb09c9378
Create Date: 2026-03-28 23:28:35.637460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63ddeee8117a'
down_revision = 'bb0bb09c9378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.alter_column('tipo_empaque',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('peso_por_pieza',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('stock_actual')
        batch_op.drop_column('stock_minimo')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.create_unique_constraint(None, ['imagen_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_minimo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stock_actual', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('peso_por_pieza',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tipo_empaque',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
