"""nomina individual y grupal

Revision ID: b05cfc031872
Revises: f5363565c632
Create Date: 2026-03-29 21:42:48.283680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b05cfc031872'
down_revision = 'f5363565c632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos_extra',
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.drop_table('compras_proveedores')
    op.drop_table('detalle_nomina')
    op.drop_table('detalle_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_table('nominas')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.alter_column('stock_actual',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('stock_minimo',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0.000'))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('imagen_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.drop_index('codigo')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', mysql.VARCHAR(length=30), nullable=True))
        batch_op.create_index('codigo', ['codigo'], unique=True)
        batch_op.alter_column('imagen_url',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.alter_column('stock_minimo',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('stock_actual',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text('0.000'))

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    op.create_table('nominas',
    sa.Column('id_nomina', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('periodo', mysql.ENUM('quincenal', 'mensual'), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.Column('total_pagado', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estatus', mysql.ENUM('borrador', 'pagada'), nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_nomina'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ordenes_produccion',
    sa.Column('id_orden', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_produccion', sa.DATE(), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('planeada', 'en_proceso', 'terminada', 'cancelada'), server_default=sa.text("'planeada'"), nullable=True),
    sa.Column('notas', mysql.TEXT(), nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='ordenes_produccion_ibfk_1'),
    sa.PrimaryKeyConstraint('id_orden'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_produccion',
    sa.Column('id_detalle', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_orden', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_receta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('piezas_producidas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_produccion.id_orden'], name='detalle_produccion_ibfk_1'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='detalle_produccion_ibfk_2'),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], name='detalle_produccion_ibfk_3'),
    sa.PrimaryKeyConstraint('id_detalle'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_nomina',
    sa.Column('id_detalle', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_nomina', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_empleado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('salario_base', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='detalle_nomina_ibfk_1'),
    sa.ForeignKeyConstraint(['id_nomina'], ['nominas.id_nomina'], name='detalle_nomina_ibfk_2'),
    sa.PrimaryKeyConstraint('id_detalle'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('compras_proveedores',
    sa.Column('id_compra', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('id_proveedor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notas', mysql.TEXT(), nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'cancelado'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='compras_proveedores_ibfk_1'),
    sa.PrimaryKeyConstraint('id_compra'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('gastos_extra')
    # ### end Alembic commands ###
