"""agregar estatus a proveedores

Revision ID: b6800216677d
Revises: 
Create Date: 2026-03-14 16:39:16.051615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6800216677d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_compras')
    op.drop_table('materias_primas')
    op.drop_table('detalle_receta')
    op.drop_table('compras_proveedores')
    op.drop_table('recetas')
    op.drop_table('detalle_produccion')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('codigo'))

    op.drop_table('productos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nombre'))

    op.drop_table('categorias')
    op.drop_table('ordenes_produccion')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nombre'))

    op.drop_table('roles')
    op.drop_table('inventario_producto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario_producto',
    sa.Column('id_inventario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_orden', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('unidad', mysql.ENUM('pieza', 'kg'), server_default=sa.text("'pieza'"), nullable=True),
    sa.Column('fecha_elaboracion', sa.DATE(), nullable=False),
    sa.Column('fecha_caducidad', sa.DATE(), nullable=False),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_produccion.id_orden'], name=op.f('inventario_producto_ibfk_2')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('inventario_producto_ibfk_1')),
    sa.PrimaryKeyConstraint('id_inventario'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    op.create_table('ordenes_produccion',
    sa.Column('id_orden', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_produccion', sa.DATE(), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('planeada', 'en_proceso', 'terminada', 'cancelada'), server_default=sa.text("'planeada'"), nullable=True),
    sa.Column('notas', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('ordenes_produccion_ibfk_1')),
    sa.PrimaryKeyConstraint('id_orden'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categorias',
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name=op.f('usuarios_ibfk_1')),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('productos',
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_venta', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario_estimado', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('imagen_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('dias_caducidad', mysql.INTEGER(), server_default=sa.text("'3'"), autoincrement=False, nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], name=op.f('productos_ibfk_1')),
    sa.PrimaryKeyConstraint('id_producto'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('codigo'), ['codigo'], unique=True)

    op.create_table('detalle_produccion',
    sa.Column('id_detalle', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_orden', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_receta', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('piezas_producidas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_produccion.id_orden'], name=op.f('detalle_produccion_ibfk_1')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('detalle_produccion_ibfk_2')),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], name=op.f('detalle_produccion_ibfk_3')),
    sa.PrimaryKeyConstraint('id_detalle'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recetas',
    sa.Column('id_receta', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rendimiento_piezas', mysql.INTEGER(), server_default=sa.text("'20'"), autoincrement=False, nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('recetas_ibfk_1')),
    sa.PrimaryKeyConstraint('id_receta'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('compras_proveedores',
    sa.Column('id_compra', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notas', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'cancelado'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name=op.f('compras_proveedores_ibfk_1')),
    sa.PrimaryKeyConstraint('id_compra'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_receta',
    sa.Column('id_detalle', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_receta', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_materia', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_por_pieza', mysql.DECIMAL(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], name=op.f('detalle_receta_ibfk_2')),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], name=op.f('detalle_receta_ibfk_1')),
    sa.PrimaryKeyConstraint('id_detalle'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('materias_primas',
    sa.Column('id_materia', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('unidad_medida', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('stock_actual', mysql.DECIMAL(precision=12, scale=3), server_default=sa.text("'0.000'"), nullable=True),
    sa.Column('stock_minimo', mysql.DECIMAL(precision=12, scale=3), server_default=sa.text("'0.000'"), nullable=True),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_ultima_compra', sa.DATE(), nullable=True),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name=op.f('materias_primas_ibfk_1')),
    sa.PrimaryKeyConstraint('id_materia'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_compras',
    sa.Column('id_detalle', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_compra', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_materia', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras_proveedores.id_compra'], name=op.f('detalle_compras_ibfk_1')),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], name=op.f('detalle_compras_ibfk_2')),
    sa.PrimaryKeyConstraint('id_detalle'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
