"""nuevos cambios2

Revision ID: b80ad5e84a40
Revises: 3f32b8d05282
Create Date: 2026-03-28 15:04:48.682418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80ad5e84a40'
down_revision = '3f32b8d05282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('imagen', sa.LargeBinary(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ordenes',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cajera', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estatus', sa.Enum('pendiente', 'completada', 'cancelada'), nullable=True),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sucursales',
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.PrimaryKeyConstraint('id_sucursal')
    )
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('empleados',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('puesto', sa.String(length=80), nullable=True),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('email')
    )
    op.create_table('materias_primas',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_compra', sa.Date(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imagen_url', sa.LargeBinary(), nullable=True),
    sa.Column('dias_caducidad', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_compra',
    sa.Column('id_detalle_compra', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.PrimaryKeyConstraint('id_detalle_compra')
    )
    op.create_table('detalle_orden',
    sa.Column('id_detalle_orden', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle_orden')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('rendimiento_piezas', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_receta'),
    sa.UniqueConstraint('id_producto')
    )
    op.create_table('detalle_receta',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id_detalle'),
    sa.UniqueConstraint('id_receta', 'id_materia', name='unique_receta_materia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_receta')
    op.drop_table('recetas')
    op.drop_table('detalle_orden')
    op.drop_table('detalle_compra')
    op.drop_table('bitacora')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('materias_primas')
    op.drop_table('empleados')
    op.drop_table('compras')
    op.drop_table('sucursales')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('ordenes')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
