"""Agregar campos de empaque a materias_primas

Revision ID: bb0bb09c9378
Revises: b80ad5e84a40
Create Date: 2026-03-28 19:35:10.424285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb0bb09c9378'
down_revision = 'b80ad5e84a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_empaque', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('piezas_por_caja', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peso_por_pieza', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stock_cajas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_piezas_sueltas', sa.Integer(), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['imagen_url'])
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.drop_column('stock_piezas_sueltas')
        batch_op.drop_column('stock_cajas')
        batch_op.drop_column('peso_por_pieza')
        batch_op.drop_column('piezas_por_caja')
        batch_op.drop_column('tipo_empaque')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
