"""nuevo

Revision ID: d31bb0f56e91
Revises: ba2ddc0b6331
Create Date: 2026-04-05 17:49:33.818672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd31bb0f56e91'
down_revision = 'ba2ddc0b6331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_compra')
    op.drop_table('bitacora')
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sucursal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_orden', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_estimada_entrega', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_entrega', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'])
        batch_op.drop_column('fecha')

    with op.batch_alter_table('detalle_orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_recetas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('costo_unitario_produccion', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('subtotal_costo', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('subtotal')
        batch_op.drop_column('precio_unitario')

    with op.batch_alter_table('detalle_receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False))
        batch_op.add_column(sa.Column('precio_por_unidad', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('costo_total_ingrediente', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.create_unique_constraint('unique_receta_materia', ['id_receta', 'id_materia'])
        batch_op.drop_column('cantidad_por_pieza')

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_contenido', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_empaque', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('piezas_por_caja', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peso_por_pieza', sa.Float(), nullable=True))
        batch_op.drop_column('stock_actual')
        batch_op.drop_column('precio_unitario')
        batch_op.drop_column('stock_minimo')
        batch_op.drop_column('fecha_ultima_compra')

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sucursal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_produccion', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('total_unidades', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('costo_total_estimado', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'])
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.drop_column('cliente_nombre')
        batch_op.drop_column('cajera')
        batch_op.drop_column('total')
        batch_op.drop_column('cliente_telefono')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.create_unique_constraint(None, ['imagen_url'])

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['telefono'])
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('rendimiento_piezas',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id_producto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rendimiento_piezas',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cajera', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('cliente_nombre', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notas')
        batch_op.drop_column('costo_total_estimado')
        batch_op.drop_column('total_unidades')
        batch_op.drop_column('fecha_produccion')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('id_sucursal')

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ultima_compra', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('stock_minimo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stock_actual', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('peso_por_pieza')
        batch_op.drop_column('piezas_por_caja')
        batch_op.drop_column('tipo_empaque')
        batch_op.drop_column('unidad_contenido')

    with op.batch_alter_table('detalle_receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_por_pieza', mysql.DECIMAL(precision=12, scale=4), nullable=False))
        batch_op.drop_constraint('unique_receta_materia', type_='unique')
        batch_op.drop_column('costo_total_ingrediente')
        batch_op.drop_column('precio_por_unidad')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('detalle_orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('subtotal', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('subtotal_costo')
        batch_op.drop_column('costo_unitario_produccion')
        batch_op.drop_column('cantidad_recetas')

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_column('notas')
        batch_op.drop_column('estado')
        batch_op.drop_column('fecha_entrega')
        batch_op.drop_column('fecha_estimada_entrega')
        batch_op.drop_column('fecha_orden')
        batch_op.drop_column('id_sucursal')

    op.create_table('bitacora',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), nullable=True),
    sa.Column('accion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tabla', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('registro_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datos_anteriores', mysql.TEXT(), nullable=True),
    sa.Column('datos_nuevos', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], name=op.f('bitacora_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_compra',
    sa.Column('id_detalle_compra', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_compra', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_materia', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], name=op.f('detalle_compra_ibfk_1')),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], name=op.f('detalle_compra_ibfk_2')),
    sa.PrimaryKeyConstraint('id_detalle_compra'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
